main:
    1. set series_fill_valve to closed
    2. set supply_valve to open
        - [p1 < 600] abort_1.1
        - [p1 > 1000] abort_2.1
    3. set series_fill_valve to open
    4. set remote_fill_valve to open
    5. [180s] set remote_fill_valve to closed
    6. set remote_vent_valve to open

abort_1:
    1. set supply_valve to closed
    2. set remote_vent_valve to open

abort_2:
    1. set supply_valve to closed
    2. set remote_vent_valve to open
