main:
    1. PRIMARY: Set series_fill_valve to closed
    2. PRIMARY: [5s] Set supply_valve to open
        - [p1 < 600] abort_1.1
        - [p1 > 1000] abort_2.1
    3. PRIMARY: Set series_fill_valve to open
    4. PRIMARY: Set remote_fill_valve to open
    5. PRIMARY: [180s] Set remote_fill_valve to closed
    6. PRIMARY: Set remote_vent_valve to open
    7. OPS: Proceed with teardown

abort_1:
    1. SECONDARY: Set supply_valve to closed
    2. SECONDARY: [10s] Set remote_vent_valve to open
    3. OPS: Proceed with teardown

abort_2:
    1. CONTROL: Set supply_valve to closed
    2. CONTROL: Set line_vent_valve to open
    3. OPS: Proceed with teardown
